const PENDING = "Pending";
const IMAGE_GENERATION = "Image Generation";
const NFT_DEPLOY = "NFT Deploy";
const NFT_MINT = "NFT Mint";
const METADATA_SETTING = "Metadata Setting";
const LIST_FOR_SALE = "List for Sale";
const COMPLETED = "Completed";
const PROGRESS_STATUS = [
  PENDING,
  IMAGE_GENERATION,
  NFT_DEPLOY,
  NFT_MINT,
  // METADATA_SETTING,
  LIST_FOR_SALE,
  COMPLETED,
];
const LARGE_COLLECTION = 5;
const SMALL_COLLECTION = 2;
const COLLECTION_TYPES = [SMALL_COLLECTION, LARGE_COLLECTION];

module.exports = {
  PROGRESS_STATUS,
  COLLECTION_TYPES,
  PENDING,
  IMAGE_GENERATION,
  NFT_DEPLOY,
  NFT_MINT,
  METADATA_SETTING,
  LIST_FOR_SALE,
  COMPLETED,
  LARGE_COLLECTION,
  SMALL_COLLECTION,
};
